import type { Invoice } from "@/types/database";

export const fallbackFactures: Invoice[] = [
  {
    id: "FAC-001",
    numero: "FAC-2026-001",
    client_id: null,
    projet_id: null,
    contrat_id: null,
    titre: "Construction Immeuble Banto",
    statut: "Payée",
    priorite: "Haute",
    montant_total: 85000000,
    date_emission: "2026-02-15",
    date_echeance: "2026-03-15",
    date_paiement: "2026-03-10",
    contenu: [],
    conditions: "",
    notes: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: "FAC-002",
    numero: "FAC-2026-002",
    client_id: null,
    projet_id: null,
    contrat_id: null,
    titre: "Rénovation Hôtel Royal",
    statut: "Impayée",
    priorite: "Haute",
    montant_total: 42500000,
    date_emission: "2026-05-01",
    date_echeance: "2026-06-01",
    date_paiement: null,
    contenu: [],
    conditions: "",
    notes: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: "FAC-003",
    numero: "FAC-2026-003",
    client_id: null,
    projet_id: null,
    contrat_id: null,
    titre: "Extension Hôpital Central",
    statut: "Envoyée",
    priorite: "Haute",
    montant_total: 120000000,
    date_emission: "2026-04-15",
    date_echeance: "2026-05-15",
    date_paiement: null,
    contenu: [],
    conditions: "",
    notes: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: "FAC-004",
    numero: "FAC-2026-004",
    client_id: null,
    projet_id: null,
    contrat_id: null,
    titre: "Complexe Sportif",
    statut: "Brouillon",
    priorite: "Haute",
    montant_total: 95000000,
    date_emission: "2026-06-01",
    date_echeance: "2026-07-01",
    date_paiement: null,
    contenu: [],
    conditions: "",
    notes: "",
    created_at: "",
    updated_at: "",
  },
  {
    id: "FAC-005",
    numero: "FAC-2026-005",
    client_id: null,
    projet_id: null,
    contrat_id: null,
    titre: "Rénovation SIEM",
    statut: "Annulée",
    priorite: "Basse",
    montant_total: 15000000,
    date_emission: "2026-01-15",
    date_echeance: "2026-02-15",
    date_paiement: null,
    contenu: [],
    conditions: "",
    notes: "",
    created_at: "",
    updated_at: "",
  },
];

export const statusColors: Record<string, string> = {
  Brouillon: "border-muted-foreground/20 bg-muted text-muted-foreground",
  Envoyée: "border-sky-500/20 bg-sky-500/10 text-sky-700 dark:text-sky-300",
  Payée:
    "border-green-500/20 bg-green-500/10 text-green-700 dark:text-green-300",
  Impayée: "border-destructive/20 bg-destructive/10 text-destructive",
  Annulée: "border-muted-foreground/20 bg-muted text-muted-foreground",
};
